
server:
    port: 9002
spring:
    application:
        name: books-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: RJHs@1328107383
        url: jdbc:mysql://localhost:3306/librarydb
        username: SATYAU3
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
logging:
    level:
        org:
            hibernate:
                sql: DEBUG