spring.application.name=spring-boot-application
server.port=8082

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:demoApp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=satya
spring.datasource.password=Satya@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform