spring.application.name=secureapp


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/exampledb
spring.datasource.username=SATYAU3
spring.datasource.password=RJHs@1328107383
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

